### ISSUE TITLE
Light theme hover on button blends with background. 

### ISSUE THREAD

**Issue by brendanfuller** [rakibulll/cardinal-hacks-website#10]
When hovering a button the button background color blends closely with the background. 

Suggestion: Make it a darker on both hover and focus respectively, assuming Chakra can support this.

![image](https://user-images.githubusercontent.com/13824197/218265355-cf9f3de5-2dce-4f41-a1d5-70916a1ff012.png)

**Comment by nickburger1** [comment]
fixed in pr #17 (second commit)
