### ISSUE TITLE
Icon constrast in cards on light theme are white

### ISSUE THREAD

**Issue by brendanfuller** [rakibulll/cardinal-hacks-website#11]
When on light theme icon displayed they are shown as white, which is the same for dark theme. 

Suggestion: Make them black and white respectively on the themes

![image](https://user-images.githubusercontent.com/13824197/218265614-c83040df-c949-4ad2-bec5-5339cd52d0cc.png)

**Comment by nickburger1** [comment]
fixed in pr #17
