### ISSUE TITLE
Accordian hover font gradient is hard to read on light theme

### ISSUE THREAD

**Issue by brendanfuller** [rakibulll/cardinal-hacks-website#12]
When hovering on an accordion to show the FAQ, the font gradient is hard to see when the text is decently long. 

Suggestion: Make it gray on hover for simplicity, which works on both light and dark modes.

![image](https://user-images.githubusercontent.com/13824197/218265653-b891362f-c467-4252-8ee8-87178ee58704.png)

> Note: The font of the image is enlarged but viewed at its normal font size it will be harder to view (2k and 4k monitors respectively)

**Comment by brendanfuller** [comment]
Thinking again, dark gray for white and maybe a lighter gray could be use for black. Ideally no gradient would be better.

**Comment by nickburger1** [comment]
fixed in pr #17 (second commit)
