### ISSUE TITLE
Navigation bar contrast with background on dark theme

### ISSUE THREAD

**Issue by brendanfuller** [rakibulll/cardinal-hacks-website#14]
The navigation bar on dark theme blends in with the background

Suggestion: Make the background lighter on dark theme, or add a border like the gradient to the navbar

![image](https://user-images.githubusercontent.com/13824197/218266021-933dc0db-e859-48e2-862d-0509b872cf37.png)

**Comment by nickburger1** [comment]
fixed in pr #17 (second commit)
