### ISSUE TITLE
Bolding the accordian titles

### ISSUE THREAD

**Issue by brendanfuller** [rakibulll/cardinal-hacks-website#15]
Currently the accordion titles are shown with a gradient when focus. Ideally making the bold for focus would provide better constrast as the body text is the same font size. 

Also see this issue for gradient related issues
 #12 

![image](https://user-images.githubusercontent.com/13824197/218266179-dba017f6-93ad-4d66-8f63-be2d34c2edf9.png)

**Comment by nickburger1** [comment]
fixed in pr #17 (second commit)
