### ISSUE TITLE
Default to dark mode?

### ISSUE THREAD

**Issue by brendanfuller** [rakibulll/cardinal-hacks-website#16]
A lot of computer science and stem related users prefer dark mode over light. Based on the Chakra docs this should be possible

https://chakra-ui.com/docs/styled-system/color-mode

From the documentation a theme prop would need to be added to this
https://github.com/rakibulll/cardinal-hacks-website/blob/726e80e88ab10ed5471b333b1f3a9d833693f139/cardinal-hack-hackathon/src/index.js#L11

And thus **nothing** in the header would need to be changed.

https://github.com/rakibulll/cardinal-hacks-website/blob/726e80e88ab10ed5471b333b1f3a9d833693f139/cardinal-hack-hackathon/src/components/Header.js#L12-L14

**Comment by nickburger1** [comment]
addressed in pr #20
